a=input('digite algo: ')
print('o tipo primitivo é: ', type(a))
print(f'{a} só tem espaços? ', a.isspace())
print(f'{a} é um numero? ', a.isnumeric())
print(f'{a} é alfabético? ', a.isalpha())
print(f'{a} é alfanumerico? ', a.isalnum())
print(f'{a} está em maisculas? ', a.isupper())
print(f'{a} está em minusculas? ', a.islower())
print(f'{a} está capitalizado? ', a.istitle())
